# Makefile.in generated by automake 1.15.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2017 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/mrwatchmaker
pkgincludedir = $(includedir)/mrwatchmaker
pkglibdir = $(libdir)/mrwatchmaker
pkglibexecdir = $(libexecdir)/mrwatchmaker
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = mrwatchmaker$(EXEEXT)
noinst_PROGRAMS = port_finder$(EXEEXT)
EXTRA_PROGRAMS = mrwatchmaker-dbg$(EXEEXT) mrwatchmaker-prf$(EXEEXT) \
	mrwatchmaker-vlg$(EXEEXT)
am__append_1 = icons/tg-timer.rc
am__append_2 = -mwindows
am__append_3 = -mconsole
am__append_4 = -mconsole
am__append_5 = -mconsole
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/attributes.m4 \
	$(top_srcdir)/version $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(dist_desktop_DATA) $(dist_mime_DATA) \
	$(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)" \
	"$(DESTDIR)$(desktopdir)" "$(DESTDIR)$(mimedir)"
PROGRAMS = $(bin_PROGRAMS) $(noinst_PROGRAMS)
am__mrwatchmaker_SOURCES_DIST = src/algo.c src/audio.c src/computer.c \
	src/config.c src/interface.c src/output_panel.c \
	src/serializer.c src/serial_motor.c src/serial_motor.h \
	src/i18n.c src/i18n.h src/tg.h icons/tg-timer.rc
am__dirstamp = $(am__leading_dot)dirstamp
am__objects_1 =  \
	icons/tg-timer.$(OBJEXT)
am_mrwatchmaker_OBJECTS = src/algo.$(OBJEXT) src/audio.$(OBJEXT) \
	src/computer.$(OBJEXT) src/config.$(OBJEXT) \
	src/interface.$(OBJEXT) src/output_panel.$(OBJEXT) \
	src/serializer.$(OBJEXT) src/serial_motor.$(OBJEXT) \
	src/i18n.$(OBJEXT) $(am__objects_1)
mrwatchmaker_OBJECTS = $(am_mrwatchmaker_OBJECTS)
mrwatchmaker_LDADD = $(LDADD)
mrwatchmaker_LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(mrwatchmaker_LDFLAGS) $(LDFLAGS) -o $@
am__mrwatchmaker_dbg_SOURCES_DIST = src/algo.c src/audio.c \
	src/computer.c src/config.c src/interface.c src/output_panel.c \
	src/serializer.c src/serial_motor.c src/serial_motor.h \
	src/i18n.c src/i18n.h src/tg.h icons/tg-timer.rc
am__objects_2 = src/mrwatchmaker_dbg-algo.$(OBJEXT) \
	src/mrwatchmaker_dbg-audio.$(OBJEXT) \
	src/mrwatchmaker_dbg-computer.$(OBJEXT) \
	src/mrwatchmaker_dbg-config.$(OBJEXT) \
	src/mrwatchmaker_dbg-interface.$(OBJEXT) \
	src/mrwatchmaker_dbg-output_panel.$(OBJEXT) \
	src/mrwatchmaker_dbg-serializer.$(OBJEXT) \
	src/mrwatchmaker_dbg-serial_motor.$(OBJEXT) \
	src/mrwatchmaker_dbg-i18n.$(OBJEXT) $(am__objects_1)
am_mrwatchmaker_dbg_OBJECTS = $(am__objects_2)
mrwatchmaker_dbg_OBJECTS = $(am_mrwatchmaker_dbg_OBJECTS)
mrwatchmaker_dbg_LDADD = $(LDADD)
mrwatchmaker_dbg_LINK = $(CCLD) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) \
	$(mrwatchmaker_dbg_LDFLAGS) $(LDFLAGS) -o $@
am__mrwatchmaker_prf_SOURCES_DIST = src/algo.c src/audio.c \
	src/computer.c src/config.c src/interface.c src/output_panel.c \
	src/serializer.c src/serial_motor.c src/serial_motor.h \
	src/i18n.c src/i18n.h src/tg.h icons/tg-timer.rc
am__objects_3 = src/mrwatchmaker_prf-algo.$(OBJEXT) \
	src/mrwatchmaker_prf-audio.$(OBJEXT) \
	src/mrwatchmaker_prf-computer.$(OBJEXT) \
	src/mrwatchmaker_prf-config.$(OBJEXT) \
	src/mrwatchmaker_prf-interface.$(OBJEXT) \
	src/mrwatchmaker_prf-output_panel.$(OBJEXT) \
	src/mrwatchmaker_prf-serializer.$(OBJEXT) \
	src/mrwatchmaker_prf-serial_motor.$(OBJEXT) \
	src/mrwatchmaker_prf-i18n.$(OBJEXT) $(am__objects_1)
am_mrwatchmaker_prf_OBJECTS = $(am__objects_3)
mrwatchmaker_prf_OBJECTS = $(am_mrwatchmaker_prf_OBJECTS)
mrwatchmaker_prf_LDADD = $(LDADD)
mrwatchmaker_prf_LINK = $(CCLD) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) \
	$(mrwatchmaker_prf_LDFLAGS) $(LDFLAGS) -o $@
am__mrwatchmaker_vlg_SOURCES_DIST = src/algo.c src/audio.c \
	src/computer.c src/config.c src/interface.c src/output_panel.c \
	src/serializer.c src/serial_motor.c src/serial_motor.h \
	src/i18n.c src/i18n.h src/tg.h icons/tg-timer.rc
am__objects_4 = src/mrwatchmaker_vlg-algo.$(OBJEXT) \
	src/mrwatchmaker_vlg-audio.$(OBJEXT) \
	src/mrwatchmaker_vlg-computer.$(OBJEXT) \
	src/mrwatchmaker_vlg-config.$(OBJEXT) \
	src/mrwatchmaker_vlg-interface.$(OBJEXT) \
	src/mrwatchmaker_vlg-output_panel.$(OBJEXT) \
	src/mrwatchmaker_vlg-serializer.$(OBJEXT) \
	src/mrwatchmaker_vlg-serial_motor.$(OBJEXT) \
	src/mrwatchmaker_vlg-i18n.$(OBJEXT) $(am__objects_1)
am_mrwatchmaker_vlg_OBJECTS = $(am__objects_4)
mrwatchmaker_vlg_OBJECTS = $(am_mrwatchmaker_vlg_OBJECTS)
mrwatchmaker_vlg_LDADD = $(LDADD)
mrwatchmaker_vlg_LINK = $(CCLD) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) \
	$(mrwatchmaker_vlg_LDFLAGS) $(LDFLAGS) -o $@
am_port_finder_OBJECTS = src/port_finder-port_finder.$(OBJEXT)
port_finder_OBJECTS = $(am_port_finder_OBJECTS)
port_finder_DEPENDENCIES =
port_finder_LINK = $(CCLD) $(port_finder_CFLAGS) $(CFLAGS) \
	$(port_finder_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(mrwatchmaker_SOURCES) $(mrwatchmaker_dbg_SOURCES) \
	$(mrwatchmaker_prf_SOURCES) $(mrwatchmaker_vlg_SOURCES) \
	$(port_finder_SOURCES)
DIST_SOURCES = $(am__mrwatchmaker_SOURCES_DIST) \
	$(am__mrwatchmaker_dbg_SOURCES_DIST) \
	$(am__mrwatchmaker_prf_SOURCES_DIST) \
	$(am__mrwatchmaker_vlg_SOURCES_DIST) $(port_finder_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(dist_man_MANS)
DATA = $(dist_desktop_DATA) $(dist_mime_DATA)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = $(SUBDIRS)
am__DIST_COMMON = $(dist_man_MANS) $(srcdir)/Makefile.in compile \
	depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /c/Users/USER/Desktop/watch_time/mrwatchmaker/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AM_LDFLAGS = -Wl,--as-needed
AUTOCONF = ${SHELL} /c/Users/USER/Desktop/watch_time/mrwatchmaker/missing autoconf
AUTOHEADER = ${SHELL} /c/Users/USER/Desktop/watch_time/mrwatchmaker/missing autoheader
AUTOMAKE = ${SHELL} /c/Users/USER/Desktop/watch_time/mrwatchmaker/missing automake-1.15
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 -Wall -Wextra
CPPFLAGS = 
CYGPATH_W = cygpath -w
DEFS = -DPACKAGE_NAME=\"MrWatchmaker\" -DPACKAGE_TARNAME=\"mrwatchmaker\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"MrWatchmaker\ 1.0\" -DPACKAGE_BUGREPORT=\"vacaboja@gmail.com\" -DPACKAGE_URL=\"https://github.com/vacaboja/tg\" -DPACKAGE=\"mrwatchmaker\" -DVERSION=\"1.0\" -DHAVE_LIBPTHREAD=1 -DHAVE_LIBM=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = .exe
FFTW_CFLAGS = -I/ucrt64/include
FFTW_LIBS = -L/ucrt64/lib -lfftw3f
GTK_CFLAGS = -I/ucrt64/include/gtk-3.0 -I/ucrt64/include/pango-1.0 -I/ucrt64/include -I/ucrt64/include/harfbuzz -I/ucrt64/include/cairo -I/ucrt64/include/freetype2 -I/ucrt64/include/pixman-1 -I/ucrt64/include/gdk-pixbuf-2.0 -I/ucrt64/include/libpng16 -I/ucrt64/include/webp -DLIBDEFLATE_DLL -I/ucrt64/include/atk-1.0 -I/ucrt64/include/fribidi -I/ucrt64/include/glib-2.0 -I/ucrt64/lib/glib-2.0/include
GTK_LIBS = -L/ucrt64/lib -lgtk-3 -lgdk-3 -lz -lgdi32 -limm32 -lshell32 -lole32 -luuid -lwinmm -ldwmapi -lsetupapi -lcfgmgr32 -lhid -lwinspool -lcomctl32 -lcomdlg32 -lpangocairo-1.0 -lpangowin32-1.0 -lpango-1.0 -lcairo-gobject -lcairo -lharfbuzz -lgdk_pixbuf-2.0 -latk-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = $(GTK_LIBS) \
       $(GTHREAD_LIBS) \
       $(PORTAUDIO_LIBS) \
       $(FFTW_LIBS) \
       -lpthread \
       -lm

LTLIBOBJS = 
MAKEINFO = ${SHELL} /c/Users/USER/Desktop/watch_time/mrwatchmaker/missing makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = mrwatchmaker
PACKAGE_BUGREPORT = vacaboja@gmail.com
PACKAGE_NAME = MrWatchmaker
PACKAGE_STRING = MrWatchmaker 1.0
PACKAGE_TARNAME = mrwatchmaker
PACKAGE_URL = https://github.com/vacaboja/tg
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = /ucrt64/lib/pkgconfig:/ucrt64/share/pkgconfig
PORTAUDIO_CFLAGS = -I/ucrt64/include
PORTAUDIO_LIBS = -L/ucrt64/lib -lportaudio
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.0
WINDRES = windres
abs_builddir = /c/Users/USER/Desktop/watch_time/mrwatchmaker
abs_srcdir = /c/Users/USER/Desktop/watch_time/mrwatchmaker
abs_top_builddir = /c/Users/USER/Desktop/watch_time/mrwatchmaker
abs_top_srcdir = /c/Users/USER/Desktop/watch_time/mrwatchmaker
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = x86_64-pc-cygwin
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /c/Users/USER/Desktop/watch_time/mrwatchmaker/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
SUBDIRS = icons
port_finder_SOURCES = src/port_finder.c
port_finder_CFLAGS = -Wall -Wextra
port_finder_LDADD = 
MOSTLYCLEANFILES = $(EXTRA_PROGRAMS)
mrwatchmaker_SOURCES = src/algo.c src/audio.c src/computer.c \
	src/config.c src/interface.c src/output_panel.c \
	src/serializer.c src/serial_motor.c src/serial_motor.h \
	src/i18n.c src/i18n.h src/tg.h $(am__append_1)
mrwatchmaker_dbg_SOURCES = $(mrwatchmaker_SOURCES)
mrwatchmaker_prf_SOURCES = $(mrwatchmaker_SOURCES)
mrwatchmaker_vlg_SOURCES = $(mrwatchmaker_SOURCES)
AM_CPPFLAGS = -DPROGRAM_NAME=\"MrWatchmaker\" -DVERSION=\"$(PACKAGE_VERSION)\"
mrwatchmaker_dbg_CPPFLAGS = $(AM_CPPFLAGS) -DDEBUG
AM_CFLAGS = $(GTK_CFLAGS) \
	    $(GTHREAD_CFLAGS) \
	    $(PORTAUDIO_CFLAGS) \
	    $(FFTW_CFLAGS)

mrwatchmaker_dbg_CFLAGS = $(AM_CFLAGS) -ggdb
mrwatchmaker_prf_CFLAGS = $(AM_CFLAGS) -pg
mrwatchmaker_vlg_CFLAGS = $(AM_CFLAGS) -g
mrwatchmaker_LDFLAGS = $(AM_LDFLAGS) $(am__append_2)
mrwatchmaker_dbg_LDFLAGS = $(AM_LDFLAGS) $(am__append_3)
mrwatchmaker_prf_LDFLAGS = $(AM_LDFLAGS) $(am__append_4)
mrwatchmaker_vlg_LDFLAGS = $(AM_LDFLAGS) $(am__append_5)
port_finder_LDFLAGS = -mconsole
desktopdir = $(datadir)/applications
dist_desktop_DATA = icons/tg-timer.desktop
mimedir = $(datadir)/mime/packages
dist_mime_DATA = icons/tg-timer.xml
dist_man_MANS = docs/tg-timer.1
EXTRA_DIST = autogen.sh \
	     icons \
	     packaging \
	     LICENSE \
	     README.md \
	     reference_9oclock.png


# 회사 가져갈 폴더: mrwatchmaker.exe + README 등
OFFICE_DIR = 회사가져갈_MrWatchmaker
all: all-recursive

.SUFFIXES:
.SUFFIXES: .c .o .obj .rc
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/algo.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/audio.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/computer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/config.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/interface.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/output_panel.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/serializer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/serial_motor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/i18n.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
icons/$(am__dirstamp):
	@$(MKDIR_P) icons
	@: > icons/$(am__dirstamp)
icons/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) icons/$(DEPDIR)
	@: > icons/$(DEPDIR)/$(am__dirstamp)
icons/tg-timer.$(OBJEXT): icons/$(am__dirstamp) \
	icons/$(DEPDIR)/$(am__dirstamp)

mrwatchmaker$(EXEEXT): $(mrwatchmaker_OBJECTS) $(mrwatchmaker_DEPENDENCIES) $(EXTRA_mrwatchmaker_DEPENDENCIES) 
	@rm -f mrwatchmaker$(EXEEXT)
	$(AM_V_CCLD)$(mrwatchmaker_LINK) $(mrwatchmaker_OBJECTS) $(mrwatchmaker_LDADD) $(LIBS)
src/mrwatchmaker_dbg-algo.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_dbg-audio.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_dbg-computer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_dbg-config.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_dbg-interface.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_dbg-output_panel.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_dbg-serializer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_dbg-serial_motor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_dbg-i18n.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

mrwatchmaker-dbg$(EXEEXT): $(mrwatchmaker_dbg_OBJECTS) $(mrwatchmaker_dbg_DEPENDENCIES) $(EXTRA_mrwatchmaker_dbg_DEPENDENCIES) 
	@rm -f mrwatchmaker-dbg$(EXEEXT)
	$(AM_V_CCLD)$(mrwatchmaker_dbg_LINK) $(mrwatchmaker_dbg_OBJECTS) $(mrwatchmaker_dbg_LDADD) $(LIBS)
src/mrwatchmaker_prf-algo.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_prf-audio.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_prf-computer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_prf-config.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_prf-interface.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_prf-output_panel.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_prf-serializer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_prf-serial_motor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_prf-i18n.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

mrwatchmaker-prf$(EXEEXT): $(mrwatchmaker_prf_OBJECTS) $(mrwatchmaker_prf_DEPENDENCIES) $(EXTRA_mrwatchmaker_prf_DEPENDENCIES) 
	@rm -f mrwatchmaker-prf$(EXEEXT)
	$(AM_V_CCLD)$(mrwatchmaker_prf_LINK) $(mrwatchmaker_prf_OBJECTS) $(mrwatchmaker_prf_LDADD) $(LIBS)
src/mrwatchmaker_vlg-algo.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_vlg-audio.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_vlg-computer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_vlg-config.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_vlg-interface.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_vlg-output_panel.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_vlg-serializer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_vlg-serial_motor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/mrwatchmaker_vlg-i18n.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

mrwatchmaker-vlg$(EXEEXT): $(mrwatchmaker_vlg_OBJECTS) $(mrwatchmaker_vlg_DEPENDENCIES) $(EXTRA_mrwatchmaker_vlg_DEPENDENCIES) 
	@rm -f mrwatchmaker-vlg$(EXEEXT)
	$(AM_V_CCLD)$(mrwatchmaker_vlg_LINK) $(mrwatchmaker_vlg_OBJECTS) $(mrwatchmaker_vlg_LDADD) $(LIBS)
src/port_finder-port_finder.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

port_finder$(EXEEXT): $(port_finder_OBJECTS) $(port_finder_DEPENDENCIES) $(EXTRA_port_finder_DEPENDENCIES) 
	@rm -f port_finder$(EXEEXT)
	$(AM_V_CCLD)$(port_finder_LINK) $(port_finder_OBJECTS) $(port_finder_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f icons/*.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/algo.Po
include src/$(DEPDIR)/audio.Po
include src/$(DEPDIR)/computer.Po
include src/$(DEPDIR)/config.Po
include src/$(DEPDIR)/i18n.Po
include src/$(DEPDIR)/interface.Po
include src/$(DEPDIR)/mrwatchmaker_dbg-algo.Po
include src/$(DEPDIR)/mrwatchmaker_dbg-audio.Po
include src/$(DEPDIR)/mrwatchmaker_dbg-computer.Po
include src/$(DEPDIR)/mrwatchmaker_dbg-config.Po
include src/$(DEPDIR)/mrwatchmaker_dbg-i18n.Po
include src/$(DEPDIR)/mrwatchmaker_dbg-interface.Po
include src/$(DEPDIR)/mrwatchmaker_dbg-output_panel.Po
include src/$(DEPDIR)/mrwatchmaker_dbg-serial_motor.Po
include src/$(DEPDIR)/mrwatchmaker_dbg-serializer.Po
include src/$(DEPDIR)/mrwatchmaker_prf-algo.Po
include src/$(DEPDIR)/mrwatchmaker_prf-audio.Po
include src/$(DEPDIR)/mrwatchmaker_prf-computer.Po
include src/$(DEPDIR)/mrwatchmaker_prf-config.Po
include src/$(DEPDIR)/mrwatchmaker_prf-i18n.Po
include src/$(DEPDIR)/mrwatchmaker_prf-interface.Po
include src/$(DEPDIR)/mrwatchmaker_prf-output_panel.Po
include src/$(DEPDIR)/mrwatchmaker_prf-serial_motor.Po
include src/$(DEPDIR)/mrwatchmaker_prf-serializer.Po
include src/$(DEPDIR)/mrwatchmaker_vlg-algo.Po
include src/$(DEPDIR)/mrwatchmaker_vlg-audio.Po
include src/$(DEPDIR)/mrwatchmaker_vlg-computer.Po
include src/$(DEPDIR)/mrwatchmaker_vlg-config.Po
include src/$(DEPDIR)/mrwatchmaker_vlg-i18n.Po
include src/$(DEPDIR)/mrwatchmaker_vlg-interface.Po
include src/$(DEPDIR)/mrwatchmaker_vlg-output_panel.Po
include src/$(DEPDIR)/mrwatchmaker_vlg-serial_motor.Po
include src/$(DEPDIR)/mrwatchmaker_vlg-serializer.Po
include src/$(DEPDIR)/output_panel.Po
include src/$(DEPDIR)/port_finder-port_finder.Po
include src/$(DEPDIR)/serial_motor.Po
include src/$(DEPDIR)/serializer.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/mrwatchmaker_dbg-algo.o: src/algo.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-algo.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-algo.Tpo -c -o src/mrwatchmaker_dbg-algo.o `test -f 'src/algo.c' || echo '$(srcdir)/'`src/algo.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-algo.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-algo.Po
#	$(AM_V_CC)source='src/algo.c' object='src/mrwatchmaker_dbg-algo.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-algo.o `test -f 'src/algo.c' || echo '$(srcdir)/'`src/algo.c

src/mrwatchmaker_dbg-algo.obj: src/algo.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-algo.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-algo.Tpo -c -o src/mrwatchmaker_dbg-algo.obj `if test -f 'src/algo.c'; then $(CYGPATH_W) 'src/algo.c'; else $(CYGPATH_W) '$(srcdir)/src/algo.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-algo.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-algo.Po
#	$(AM_V_CC)source='src/algo.c' object='src/mrwatchmaker_dbg-algo.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-algo.obj `if test -f 'src/algo.c'; then $(CYGPATH_W) 'src/algo.c'; else $(CYGPATH_W) '$(srcdir)/src/algo.c'; fi`

src/mrwatchmaker_dbg-audio.o: src/audio.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-audio.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-audio.Tpo -c -o src/mrwatchmaker_dbg-audio.o `test -f 'src/audio.c' || echo '$(srcdir)/'`src/audio.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-audio.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-audio.Po
#	$(AM_V_CC)source='src/audio.c' object='src/mrwatchmaker_dbg-audio.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-audio.o `test -f 'src/audio.c' || echo '$(srcdir)/'`src/audio.c

src/mrwatchmaker_dbg-audio.obj: src/audio.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-audio.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-audio.Tpo -c -o src/mrwatchmaker_dbg-audio.obj `if test -f 'src/audio.c'; then $(CYGPATH_W) 'src/audio.c'; else $(CYGPATH_W) '$(srcdir)/src/audio.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-audio.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-audio.Po
#	$(AM_V_CC)source='src/audio.c' object='src/mrwatchmaker_dbg-audio.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-audio.obj `if test -f 'src/audio.c'; then $(CYGPATH_W) 'src/audio.c'; else $(CYGPATH_W) '$(srcdir)/src/audio.c'; fi`

src/mrwatchmaker_dbg-computer.o: src/computer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-computer.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-computer.Tpo -c -o src/mrwatchmaker_dbg-computer.o `test -f 'src/computer.c' || echo '$(srcdir)/'`src/computer.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-computer.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-computer.Po
#	$(AM_V_CC)source='src/computer.c' object='src/mrwatchmaker_dbg-computer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-computer.o `test -f 'src/computer.c' || echo '$(srcdir)/'`src/computer.c

src/mrwatchmaker_dbg-computer.obj: src/computer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-computer.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-computer.Tpo -c -o src/mrwatchmaker_dbg-computer.obj `if test -f 'src/computer.c'; then $(CYGPATH_W) 'src/computer.c'; else $(CYGPATH_W) '$(srcdir)/src/computer.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-computer.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-computer.Po
#	$(AM_V_CC)source='src/computer.c' object='src/mrwatchmaker_dbg-computer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-computer.obj `if test -f 'src/computer.c'; then $(CYGPATH_W) 'src/computer.c'; else $(CYGPATH_W) '$(srcdir)/src/computer.c'; fi`

src/mrwatchmaker_dbg-config.o: src/config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-config.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-config.Tpo -c -o src/mrwatchmaker_dbg-config.o `test -f 'src/config.c' || echo '$(srcdir)/'`src/config.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-config.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-config.Po
#	$(AM_V_CC)source='src/config.c' object='src/mrwatchmaker_dbg-config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-config.o `test -f 'src/config.c' || echo '$(srcdir)/'`src/config.c

src/mrwatchmaker_dbg-config.obj: src/config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-config.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-config.Tpo -c -o src/mrwatchmaker_dbg-config.obj `if test -f 'src/config.c'; then $(CYGPATH_W) 'src/config.c'; else $(CYGPATH_W) '$(srcdir)/src/config.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-config.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-config.Po
#	$(AM_V_CC)source='src/config.c' object='src/mrwatchmaker_dbg-config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-config.obj `if test -f 'src/config.c'; then $(CYGPATH_W) 'src/config.c'; else $(CYGPATH_W) '$(srcdir)/src/config.c'; fi`

src/mrwatchmaker_dbg-interface.o: src/interface.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-interface.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-interface.Tpo -c -o src/mrwatchmaker_dbg-interface.o `test -f 'src/interface.c' || echo '$(srcdir)/'`src/interface.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-interface.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-interface.Po
#	$(AM_V_CC)source='src/interface.c' object='src/mrwatchmaker_dbg-interface.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-interface.o `test -f 'src/interface.c' || echo '$(srcdir)/'`src/interface.c

src/mrwatchmaker_dbg-interface.obj: src/interface.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-interface.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-interface.Tpo -c -o src/mrwatchmaker_dbg-interface.obj `if test -f 'src/interface.c'; then $(CYGPATH_W) 'src/interface.c'; else $(CYGPATH_W) '$(srcdir)/src/interface.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-interface.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-interface.Po
#	$(AM_V_CC)source='src/interface.c' object='src/mrwatchmaker_dbg-interface.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-interface.obj `if test -f 'src/interface.c'; then $(CYGPATH_W) 'src/interface.c'; else $(CYGPATH_W) '$(srcdir)/src/interface.c'; fi`

src/mrwatchmaker_dbg-output_panel.o: src/output_panel.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-output_panel.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-output_panel.Tpo -c -o src/mrwatchmaker_dbg-output_panel.o `test -f 'src/output_panel.c' || echo '$(srcdir)/'`src/output_panel.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-output_panel.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-output_panel.Po
#	$(AM_V_CC)source='src/output_panel.c' object='src/mrwatchmaker_dbg-output_panel.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-output_panel.o `test -f 'src/output_panel.c' || echo '$(srcdir)/'`src/output_panel.c

src/mrwatchmaker_dbg-output_panel.obj: src/output_panel.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-output_panel.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-output_panel.Tpo -c -o src/mrwatchmaker_dbg-output_panel.obj `if test -f 'src/output_panel.c'; then $(CYGPATH_W) 'src/output_panel.c'; else $(CYGPATH_W) '$(srcdir)/src/output_panel.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-output_panel.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-output_panel.Po
#	$(AM_V_CC)source='src/output_panel.c' object='src/mrwatchmaker_dbg-output_panel.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-output_panel.obj `if test -f 'src/output_panel.c'; then $(CYGPATH_W) 'src/output_panel.c'; else $(CYGPATH_W) '$(srcdir)/src/output_panel.c'; fi`

src/mrwatchmaker_dbg-serializer.o: src/serializer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-serializer.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-serializer.Tpo -c -o src/mrwatchmaker_dbg-serializer.o `test -f 'src/serializer.c' || echo '$(srcdir)/'`src/serializer.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-serializer.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-serializer.Po
#	$(AM_V_CC)source='src/serializer.c' object='src/mrwatchmaker_dbg-serializer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-serializer.o `test -f 'src/serializer.c' || echo '$(srcdir)/'`src/serializer.c

src/mrwatchmaker_dbg-serializer.obj: src/serializer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-serializer.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-serializer.Tpo -c -o src/mrwatchmaker_dbg-serializer.obj `if test -f 'src/serializer.c'; then $(CYGPATH_W) 'src/serializer.c'; else $(CYGPATH_W) '$(srcdir)/src/serializer.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-serializer.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-serializer.Po
#	$(AM_V_CC)source='src/serializer.c' object='src/mrwatchmaker_dbg-serializer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-serializer.obj `if test -f 'src/serializer.c'; then $(CYGPATH_W) 'src/serializer.c'; else $(CYGPATH_W) '$(srcdir)/src/serializer.c'; fi`

src/mrwatchmaker_dbg-serial_motor.o: src/serial_motor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-serial_motor.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-serial_motor.Tpo -c -o src/mrwatchmaker_dbg-serial_motor.o `test -f 'src/serial_motor.c' || echo '$(srcdir)/'`src/serial_motor.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-serial_motor.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-serial_motor.Po
#	$(AM_V_CC)source='src/serial_motor.c' object='src/mrwatchmaker_dbg-serial_motor.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-serial_motor.o `test -f 'src/serial_motor.c' || echo '$(srcdir)/'`src/serial_motor.c

src/mrwatchmaker_dbg-serial_motor.obj: src/serial_motor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-serial_motor.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-serial_motor.Tpo -c -o src/mrwatchmaker_dbg-serial_motor.obj `if test -f 'src/serial_motor.c'; then $(CYGPATH_W) 'src/serial_motor.c'; else $(CYGPATH_W) '$(srcdir)/src/serial_motor.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-serial_motor.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-serial_motor.Po
#	$(AM_V_CC)source='src/serial_motor.c' object='src/mrwatchmaker_dbg-serial_motor.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-serial_motor.obj `if test -f 'src/serial_motor.c'; then $(CYGPATH_W) 'src/serial_motor.c'; else $(CYGPATH_W) '$(srcdir)/src/serial_motor.c'; fi`

src/mrwatchmaker_dbg-i18n.o: src/i18n.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-i18n.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-i18n.Tpo -c -o src/mrwatchmaker_dbg-i18n.o `test -f 'src/i18n.c' || echo '$(srcdir)/'`src/i18n.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-i18n.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-i18n.Po
#	$(AM_V_CC)source='src/i18n.c' object='src/mrwatchmaker_dbg-i18n.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-i18n.o `test -f 'src/i18n.c' || echo '$(srcdir)/'`src/i18n.c

src/mrwatchmaker_dbg-i18n.obj: src/i18n.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_dbg-i18n.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_dbg-i18n.Tpo -c -o src/mrwatchmaker_dbg-i18n.obj `if test -f 'src/i18n.c'; then $(CYGPATH_W) 'src/i18n.c'; else $(CYGPATH_W) '$(srcdir)/src/i18n.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_dbg-i18n.Tpo src/$(DEPDIR)/mrwatchmaker_dbg-i18n.Po
#	$(AM_V_CC)source='src/i18n.c' object='src/mrwatchmaker_dbg-i18n.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mrwatchmaker_dbg_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_dbg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_dbg-i18n.obj `if test -f 'src/i18n.c'; then $(CYGPATH_W) 'src/i18n.c'; else $(CYGPATH_W) '$(srcdir)/src/i18n.c'; fi`

src/mrwatchmaker_prf-algo.o: src/algo.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-algo.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-algo.Tpo -c -o src/mrwatchmaker_prf-algo.o `test -f 'src/algo.c' || echo '$(srcdir)/'`src/algo.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-algo.Tpo src/$(DEPDIR)/mrwatchmaker_prf-algo.Po
#	$(AM_V_CC)source='src/algo.c' object='src/mrwatchmaker_prf-algo.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-algo.o `test -f 'src/algo.c' || echo '$(srcdir)/'`src/algo.c

src/mrwatchmaker_prf-algo.obj: src/algo.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-algo.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-algo.Tpo -c -o src/mrwatchmaker_prf-algo.obj `if test -f 'src/algo.c'; then $(CYGPATH_W) 'src/algo.c'; else $(CYGPATH_W) '$(srcdir)/src/algo.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-algo.Tpo src/$(DEPDIR)/mrwatchmaker_prf-algo.Po
#	$(AM_V_CC)source='src/algo.c' object='src/mrwatchmaker_prf-algo.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-algo.obj `if test -f 'src/algo.c'; then $(CYGPATH_W) 'src/algo.c'; else $(CYGPATH_W) '$(srcdir)/src/algo.c'; fi`

src/mrwatchmaker_prf-audio.o: src/audio.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-audio.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-audio.Tpo -c -o src/mrwatchmaker_prf-audio.o `test -f 'src/audio.c' || echo '$(srcdir)/'`src/audio.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-audio.Tpo src/$(DEPDIR)/mrwatchmaker_prf-audio.Po
#	$(AM_V_CC)source='src/audio.c' object='src/mrwatchmaker_prf-audio.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-audio.o `test -f 'src/audio.c' || echo '$(srcdir)/'`src/audio.c

src/mrwatchmaker_prf-audio.obj: src/audio.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-audio.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-audio.Tpo -c -o src/mrwatchmaker_prf-audio.obj `if test -f 'src/audio.c'; then $(CYGPATH_W) 'src/audio.c'; else $(CYGPATH_W) '$(srcdir)/src/audio.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-audio.Tpo src/$(DEPDIR)/mrwatchmaker_prf-audio.Po
#	$(AM_V_CC)source='src/audio.c' object='src/mrwatchmaker_prf-audio.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-audio.obj `if test -f 'src/audio.c'; then $(CYGPATH_W) 'src/audio.c'; else $(CYGPATH_W) '$(srcdir)/src/audio.c'; fi`

src/mrwatchmaker_prf-computer.o: src/computer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-computer.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-computer.Tpo -c -o src/mrwatchmaker_prf-computer.o `test -f 'src/computer.c' || echo '$(srcdir)/'`src/computer.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-computer.Tpo src/$(DEPDIR)/mrwatchmaker_prf-computer.Po
#	$(AM_V_CC)source='src/computer.c' object='src/mrwatchmaker_prf-computer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-computer.o `test -f 'src/computer.c' || echo '$(srcdir)/'`src/computer.c

src/mrwatchmaker_prf-computer.obj: src/computer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-computer.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-computer.Tpo -c -o src/mrwatchmaker_prf-computer.obj `if test -f 'src/computer.c'; then $(CYGPATH_W) 'src/computer.c'; else $(CYGPATH_W) '$(srcdir)/src/computer.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-computer.Tpo src/$(DEPDIR)/mrwatchmaker_prf-computer.Po
#	$(AM_V_CC)source='src/computer.c' object='src/mrwatchmaker_prf-computer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-computer.obj `if test -f 'src/computer.c'; then $(CYGPATH_W) 'src/computer.c'; else $(CYGPATH_W) '$(srcdir)/src/computer.c'; fi`

src/mrwatchmaker_prf-config.o: src/config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-config.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-config.Tpo -c -o src/mrwatchmaker_prf-config.o `test -f 'src/config.c' || echo '$(srcdir)/'`src/config.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-config.Tpo src/$(DEPDIR)/mrwatchmaker_prf-config.Po
#	$(AM_V_CC)source='src/config.c' object='src/mrwatchmaker_prf-config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-config.o `test -f 'src/config.c' || echo '$(srcdir)/'`src/config.c

src/mrwatchmaker_prf-config.obj: src/config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-config.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-config.Tpo -c -o src/mrwatchmaker_prf-config.obj `if test -f 'src/config.c'; then $(CYGPATH_W) 'src/config.c'; else $(CYGPATH_W) '$(srcdir)/src/config.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-config.Tpo src/$(DEPDIR)/mrwatchmaker_prf-config.Po
#	$(AM_V_CC)source='src/config.c' object='src/mrwatchmaker_prf-config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-config.obj `if test -f 'src/config.c'; then $(CYGPATH_W) 'src/config.c'; else $(CYGPATH_W) '$(srcdir)/src/config.c'; fi`

src/mrwatchmaker_prf-interface.o: src/interface.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-interface.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-interface.Tpo -c -o src/mrwatchmaker_prf-interface.o `test -f 'src/interface.c' || echo '$(srcdir)/'`src/interface.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-interface.Tpo src/$(DEPDIR)/mrwatchmaker_prf-interface.Po
#	$(AM_V_CC)source='src/interface.c' object='src/mrwatchmaker_prf-interface.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-interface.o `test -f 'src/interface.c' || echo '$(srcdir)/'`src/interface.c

src/mrwatchmaker_prf-interface.obj: src/interface.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-interface.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-interface.Tpo -c -o src/mrwatchmaker_prf-interface.obj `if test -f 'src/interface.c'; then $(CYGPATH_W) 'src/interface.c'; else $(CYGPATH_W) '$(srcdir)/src/interface.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-interface.Tpo src/$(DEPDIR)/mrwatchmaker_prf-interface.Po
#	$(AM_V_CC)source='src/interface.c' object='src/mrwatchmaker_prf-interface.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-interface.obj `if test -f 'src/interface.c'; then $(CYGPATH_W) 'src/interface.c'; else $(CYGPATH_W) '$(srcdir)/src/interface.c'; fi`

src/mrwatchmaker_prf-output_panel.o: src/output_panel.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-output_panel.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-output_panel.Tpo -c -o src/mrwatchmaker_prf-output_panel.o `test -f 'src/output_panel.c' || echo '$(srcdir)/'`src/output_panel.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-output_panel.Tpo src/$(DEPDIR)/mrwatchmaker_prf-output_panel.Po
#	$(AM_V_CC)source='src/output_panel.c' object='src/mrwatchmaker_prf-output_panel.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-output_panel.o `test -f 'src/output_panel.c' || echo '$(srcdir)/'`src/output_panel.c

src/mrwatchmaker_prf-output_panel.obj: src/output_panel.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-output_panel.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-output_panel.Tpo -c -o src/mrwatchmaker_prf-output_panel.obj `if test -f 'src/output_panel.c'; then $(CYGPATH_W) 'src/output_panel.c'; else $(CYGPATH_W) '$(srcdir)/src/output_panel.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-output_panel.Tpo src/$(DEPDIR)/mrwatchmaker_prf-output_panel.Po
#	$(AM_V_CC)source='src/output_panel.c' object='src/mrwatchmaker_prf-output_panel.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-output_panel.obj `if test -f 'src/output_panel.c'; then $(CYGPATH_W) 'src/output_panel.c'; else $(CYGPATH_W) '$(srcdir)/src/output_panel.c'; fi`

src/mrwatchmaker_prf-serializer.o: src/serializer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-serializer.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-serializer.Tpo -c -o src/mrwatchmaker_prf-serializer.o `test -f 'src/serializer.c' || echo '$(srcdir)/'`src/serializer.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-serializer.Tpo src/$(DEPDIR)/mrwatchmaker_prf-serializer.Po
#	$(AM_V_CC)source='src/serializer.c' object='src/mrwatchmaker_prf-serializer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-serializer.o `test -f 'src/serializer.c' || echo '$(srcdir)/'`src/serializer.c

src/mrwatchmaker_prf-serializer.obj: src/serializer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-serializer.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-serializer.Tpo -c -o src/mrwatchmaker_prf-serializer.obj `if test -f 'src/serializer.c'; then $(CYGPATH_W) 'src/serializer.c'; else $(CYGPATH_W) '$(srcdir)/src/serializer.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-serializer.Tpo src/$(DEPDIR)/mrwatchmaker_prf-serializer.Po
#	$(AM_V_CC)source='src/serializer.c' object='src/mrwatchmaker_prf-serializer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-serializer.obj `if test -f 'src/serializer.c'; then $(CYGPATH_W) 'src/serializer.c'; else $(CYGPATH_W) '$(srcdir)/src/serializer.c'; fi`

src/mrwatchmaker_prf-serial_motor.o: src/serial_motor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-serial_motor.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-serial_motor.Tpo -c -o src/mrwatchmaker_prf-serial_motor.o `test -f 'src/serial_motor.c' || echo '$(srcdir)/'`src/serial_motor.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-serial_motor.Tpo src/$(DEPDIR)/mrwatchmaker_prf-serial_motor.Po
#	$(AM_V_CC)source='src/serial_motor.c' object='src/mrwatchmaker_prf-serial_motor.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-serial_motor.o `test -f 'src/serial_motor.c' || echo '$(srcdir)/'`src/serial_motor.c

src/mrwatchmaker_prf-serial_motor.obj: src/serial_motor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-serial_motor.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-serial_motor.Tpo -c -o src/mrwatchmaker_prf-serial_motor.obj `if test -f 'src/serial_motor.c'; then $(CYGPATH_W) 'src/serial_motor.c'; else $(CYGPATH_W) '$(srcdir)/src/serial_motor.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-serial_motor.Tpo src/$(DEPDIR)/mrwatchmaker_prf-serial_motor.Po
#	$(AM_V_CC)source='src/serial_motor.c' object='src/mrwatchmaker_prf-serial_motor.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-serial_motor.obj `if test -f 'src/serial_motor.c'; then $(CYGPATH_W) 'src/serial_motor.c'; else $(CYGPATH_W) '$(srcdir)/src/serial_motor.c'; fi`

src/mrwatchmaker_prf-i18n.o: src/i18n.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-i18n.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-i18n.Tpo -c -o src/mrwatchmaker_prf-i18n.o `test -f 'src/i18n.c' || echo '$(srcdir)/'`src/i18n.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-i18n.Tpo src/$(DEPDIR)/mrwatchmaker_prf-i18n.Po
#	$(AM_V_CC)source='src/i18n.c' object='src/mrwatchmaker_prf-i18n.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-i18n.o `test -f 'src/i18n.c' || echo '$(srcdir)/'`src/i18n.c

src/mrwatchmaker_prf-i18n.obj: src/i18n.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_prf-i18n.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_prf-i18n.Tpo -c -o src/mrwatchmaker_prf-i18n.obj `if test -f 'src/i18n.c'; then $(CYGPATH_W) 'src/i18n.c'; else $(CYGPATH_W) '$(srcdir)/src/i18n.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_prf-i18n.Tpo src/$(DEPDIR)/mrwatchmaker_prf-i18n.Po
#	$(AM_V_CC)source='src/i18n.c' object='src/mrwatchmaker_prf-i18n.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_prf_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_prf-i18n.obj `if test -f 'src/i18n.c'; then $(CYGPATH_W) 'src/i18n.c'; else $(CYGPATH_W) '$(srcdir)/src/i18n.c'; fi`

src/mrwatchmaker_vlg-algo.o: src/algo.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-algo.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-algo.Tpo -c -o src/mrwatchmaker_vlg-algo.o `test -f 'src/algo.c' || echo '$(srcdir)/'`src/algo.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-algo.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-algo.Po
#	$(AM_V_CC)source='src/algo.c' object='src/mrwatchmaker_vlg-algo.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-algo.o `test -f 'src/algo.c' || echo '$(srcdir)/'`src/algo.c

src/mrwatchmaker_vlg-algo.obj: src/algo.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-algo.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-algo.Tpo -c -o src/mrwatchmaker_vlg-algo.obj `if test -f 'src/algo.c'; then $(CYGPATH_W) 'src/algo.c'; else $(CYGPATH_W) '$(srcdir)/src/algo.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-algo.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-algo.Po
#	$(AM_V_CC)source='src/algo.c' object='src/mrwatchmaker_vlg-algo.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-algo.obj `if test -f 'src/algo.c'; then $(CYGPATH_W) 'src/algo.c'; else $(CYGPATH_W) '$(srcdir)/src/algo.c'; fi`

src/mrwatchmaker_vlg-audio.o: src/audio.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-audio.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-audio.Tpo -c -o src/mrwatchmaker_vlg-audio.o `test -f 'src/audio.c' || echo '$(srcdir)/'`src/audio.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-audio.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-audio.Po
#	$(AM_V_CC)source='src/audio.c' object='src/mrwatchmaker_vlg-audio.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-audio.o `test -f 'src/audio.c' || echo '$(srcdir)/'`src/audio.c

src/mrwatchmaker_vlg-audio.obj: src/audio.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-audio.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-audio.Tpo -c -o src/mrwatchmaker_vlg-audio.obj `if test -f 'src/audio.c'; then $(CYGPATH_W) 'src/audio.c'; else $(CYGPATH_W) '$(srcdir)/src/audio.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-audio.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-audio.Po
#	$(AM_V_CC)source='src/audio.c' object='src/mrwatchmaker_vlg-audio.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-audio.obj `if test -f 'src/audio.c'; then $(CYGPATH_W) 'src/audio.c'; else $(CYGPATH_W) '$(srcdir)/src/audio.c'; fi`

src/mrwatchmaker_vlg-computer.o: src/computer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-computer.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-computer.Tpo -c -o src/mrwatchmaker_vlg-computer.o `test -f 'src/computer.c' || echo '$(srcdir)/'`src/computer.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-computer.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-computer.Po
#	$(AM_V_CC)source='src/computer.c' object='src/mrwatchmaker_vlg-computer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-computer.o `test -f 'src/computer.c' || echo '$(srcdir)/'`src/computer.c

src/mrwatchmaker_vlg-computer.obj: src/computer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-computer.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-computer.Tpo -c -o src/mrwatchmaker_vlg-computer.obj `if test -f 'src/computer.c'; then $(CYGPATH_W) 'src/computer.c'; else $(CYGPATH_W) '$(srcdir)/src/computer.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-computer.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-computer.Po
#	$(AM_V_CC)source='src/computer.c' object='src/mrwatchmaker_vlg-computer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-computer.obj `if test -f 'src/computer.c'; then $(CYGPATH_W) 'src/computer.c'; else $(CYGPATH_W) '$(srcdir)/src/computer.c'; fi`

src/mrwatchmaker_vlg-config.o: src/config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-config.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-config.Tpo -c -o src/mrwatchmaker_vlg-config.o `test -f 'src/config.c' || echo '$(srcdir)/'`src/config.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-config.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-config.Po
#	$(AM_V_CC)source='src/config.c' object='src/mrwatchmaker_vlg-config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-config.o `test -f 'src/config.c' || echo '$(srcdir)/'`src/config.c

src/mrwatchmaker_vlg-config.obj: src/config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-config.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-config.Tpo -c -o src/mrwatchmaker_vlg-config.obj `if test -f 'src/config.c'; then $(CYGPATH_W) 'src/config.c'; else $(CYGPATH_W) '$(srcdir)/src/config.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-config.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-config.Po
#	$(AM_V_CC)source='src/config.c' object='src/mrwatchmaker_vlg-config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-config.obj `if test -f 'src/config.c'; then $(CYGPATH_W) 'src/config.c'; else $(CYGPATH_W) '$(srcdir)/src/config.c'; fi`

src/mrwatchmaker_vlg-interface.o: src/interface.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-interface.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-interface.Tpo -c -o src/mrwatchmaker_vlg-interface.o `test -f 'src/interface.c' || echo '$(srcdir)/'`src/interface.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-interface.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-interface.Po
#	$(AM_V_CC)source='src/interface.c' object='src/mrwatchmaker_vlg-interface.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-interface.o `test -f 'src/interface.c' || echo '$(srcdir)/'`src/interface.c

src/mrwatchmaker_vlg-interface.obj: src/interface.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-interface.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-interface.Tpo -c -o src/mrwatchmaker_vlg-interface.obj `if test -f 'src/interface.c'; then $(CYGPATH_W) 'src/interface.c'; else $(CYGPATH_W) '$(srcdir)/src/interface.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-interface.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-interface.Po
#	$(AM_V_CC)source='src/interface.c' object='src/mrwatchmaker_vlg-interface.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-interface.obj `if test -f 'src/interface.c'; then $(CYGPATH_W) 'src/interface.c'; else $(CYGPATH_W) '$(srcdir)/src/interface.c'; fi`

src/mrwatchmaker_vlg-output_panel.o: src/output_panel.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-output_panel.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-output_panel.Tpo -c -o src/mrwatchmaker_vlg-output_panel.o `test -f 'src/output_panel.c' || echo '$(srcdir)/'`src/output_panel.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-output_panel.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-output_panel.Po
#	$(AM_V_CC)source='src/output_panel.c' object='src/mrwatchmaker_vlg-output_panel.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-output_panel.o `test -f 'src/output_panel.c' || echo '$(srcdir)/'`src/output_panel.c

src/mrwatchmaker_vlg-output_panel.obj: src/output_panel.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-output_panel.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-output_panel.Tpo -c -o src/mrwatchmaker_vlg-output_panel.obj `if test -f 'src/output_panel.c'; then $(CYGPATH_W) 'src/output_panel.c'; else $(CYGPATH_W) '$(srcdir)/src/output_panel.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-output_panel.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-output_panel.Po
#	$(AM_V_CC)source='src/output_panel.c' object='src/mrwatchmaker_vlg-output_panel.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-output_panel.obj `if test -f 'src/output_panel.c'; then $(CYGPATH_W) 'src/output_panel.c'; else $(CYGPATH_W) '$(srcdir)/src/output_panel.c'; fi`

src/mrwatchmaker_vlg-serializer.o: src/serializer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-serializer.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-serializer.Tpo -c -o src/mrwatchmaker_vlg-serializer.o `test -f 'src/serializer.c' || echo '$(srcdir)/'`src/serializer.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-serializer.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-serializer.Po
#	$(AM_V_CC)source='src/serializer.c' object='src/mrwatchmaker_vlg-serializer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-serializer.o `test -f 'src/serializer.c' || echo '$(srcdir)/'`src/serializer.c

src/mrwatchmaker_vlg-serializer.obj: src/serializer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-serializer.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-serializer.Tpo -c -o src/mrwatchmaker_vlg-serializer.obj `if test -f 'src/serializer.c'; then $(CYGPATH_W) 'src/serializer.c'; else $(CYGPATH_W) '$(srcdir)/src/serializer.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-serializer.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-serializer.Po
#	$(AM_V_CC)source='src/serializer.c' object='src/mrwatchmaker_vlg-serializer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-serializer.obj `if test -f 'src/serializer.c'; then $(CYGPATH_W) 'src/serializer.c'; else $(CYGPATH_W) '$(srcdir)/src/serializer.c'; fi`

src/mrwatchmaker_vlg-serial_motor.o: src/serial_motor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-serial_motor.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-serial_motor.Tpo -c -o src/mrwatchmaker_vlg-serial_motor.o `test -f 'src/serial_motor.c' || echo '$(srcdir)/'`src/serial_motor.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-serial_motor.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-serial_motor.Po
#	$(AM_V_CC)source='src/serial_motor.c' object='src/mrwatchmaker_vlg-serial_motor.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-serial_motor.o `test -f 'src/serial_motor.c' || echo '$(srcdir)/'`src/serial_motor.c

src/mrwatchmaker_vlg-serial_motor.obj: src/serial_motor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-serial_motor.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-serial_motor.Tpo -c -o src/mrwatchmaker_vlg-serial_motor.obj `if test -f 'src/serial_motor.c'; then $(CYGPATH_W) 'src/serial_motor.c'; else $(CYGPATH_W) '$(srcdir)/src/serial_motor.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-serial_motor.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-serial_motor.Po
#	$(AM_V_CC)source='src/serial_motor.c' object='src/mrwatchmaker_vlg-serial_motor.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-serial_motor.obj `if test -f 'src/serial_motor.c'; then $(CYGPATH_W) 'src/serial_motor.c'; else $(CYGPATH_W) '$(srcdir)/src/serial_motor.c'; fi`

src/mrwatchmaker_vlg-i18n.o: src/i18n.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-i18n.o -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-i18n.Tpo -c -o src/mrwatchmaker_vlg-i18n.o `test -f 'src/i18n.c' || echo '$(srcdir)/'`src/i18n.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-i18n.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-i18n.Po
#	$(AM_V_CC)source='src/i18n.c' object='src/mrwatchmaker_vlg-i18n.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-i18n.o `test -f 'src/i18n.c' || echo '$(srcdir)/'`src/i18n.c

src/mrwatchmaker_vlg-i18n.obj: src/i18n.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -MT src/mrwatchmaker_vlg-i18n.obj -MD -MP -MF src/$(DEPDIR)/mrwatchmaker_vlg-i18n.Tpo -c -o src/mrwatchmaker_vlg-i18n.obj `if test -f 'src/i18n.c'; then $(CYGPATH_W) 'src/i18n.c'; else $(CYGPATH_W) '$(srcdir)/src/i18n.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/mrwatchmaker_vlg-i18n.Tpo src/$(DEPDIR)/mrwatchmaker_vlg-i18n.Po
#	$(AM_V_CC)source='src/i18n.c' object='src/mrwatchmaker_vlg-i18n.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(mrwatchmaker_vlg_CFLAGS) $(CFLAGS) -c -o src/mrwatchmaker_vlg-i18n.obj `if test -f 'src/i18n.c'; then $(CYGPATH_W) 'src/i18n.c'; else $(CYGPATH_W) '$(srcdir)/src/i18n.c'; fi`

src/port_finder-port_finder.o: src/port_finder.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(port_finder_CFLAGS) $(CFLAGS) -MT src/port_finder-port_finder.o -MD -MP -MF src/$(DEPDIR)/port_finder-port_finder.Tpo -c -o src/port_finder-port_finder.o `test -f 'src/port_finder.c' || echo '$(srcdir)/'`src/port_finder.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/port_finder-port_finder.Tpo src/$(DEPDIR)/port_finder-port_finder.Po
#	$(AM_V_CC)source='src/port_finder.c' object='src/port_finder-port_finder.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(port_finder_CFLAGS) $(CFLAGS) -c -o src/port_finder-port_finder.o `test -f 'src/port_finder.c' || echo '$(srcdir)/'`src/port_finder.c

src/port_finder-port_finder.obj: src/port_finder.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(port_finder_CFLAGS) $(CFLAGS) -MT src/port_finder-port_finder.obj -MD -MP -MF src/$(DEPDIR)/port_finder-port_finder.Tpo -c -o src/port_finder-port_finder.obj `if test -f 'src/port_finder.c'; then $(CYGPATH_W) 'src/port_finder.c'; else $(CYGPATH_W) '$(srcdir)/src/port_finder.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/port_finder-port_finder.Tpo src/$(DEPDIR)/port_finder-port_finder.Po
#	$(AM_V_CC)source='src/port_finder.c' object='src/port_finder-port_finder.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(port_finder_CFLAGS) $(CFLAGS) -c -o src/port_finder-port_finder.obj `if test -f 'src/port_finder.c'; then $(CYGPATH_W) 'src/port_finder.c'; else $(CYGPATH_W) '$(srcdir)/src/port_finder.c'; fi`
install-man1: $(dist_man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(dist_man_MANS)'; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.1[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)
install-dist_desktopDATA: $(dist_desktop_DATA)
	@$(NORMAL_INSTALL)
	@list='$(dist_desktop_DATA)'; test -n "$(desktopdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(desktopdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(desktopdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(desktopdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(desktopdir)" || exit $$?; \
	done

uninstall-dist_desktopDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_desktop_DATA)'; test -n "$(desktopdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(desktopdir)'; $(am__uninstall_files_from_dir)
install-dist_mimeDATA: $(dist_mime_DATA)
	@$(NORMAL_INSTALL)
	@list='$(dist_mime_DATA)'; test -n "$(mimedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(mimedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(mimedir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(mimedir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(mimedir)" || exit $$?; \
	done

uninstall-dist_mimeDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_mime_DATA)'; test -n "$(mimedir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(mimedir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS) $(MANS) $(DATA)
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)" "$(DESTDIR)$(desktopdir)" "$(DESTDIR)$(mimedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:
	-test -z "$(MOSTLYCLEANFILES)" || rm -f $(MOSTLYCLEANFILES)

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f icons/$(DEPDIR)/$(am__dirstamp)
	-rm -f icons/$(am__dirstamp)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-noinstPROGRAMS \
	mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-dist_desktopDATA install-dist_mimeDATA \
	install-man

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man: install-man1

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-dist_desktopDATA \
	uninstall-dist_mimeDATA uninstall-man

uninstall-man: uninstall-man1

.MAKE: $(am__recursive_targets) install-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-binPROGRAMS \
	clean-cscope clean-generic clean-noinstPROGRAMS cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am \
	install-dist_desktopDATA install-dist_mimeDATA install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-man1 install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-dist_desktopDATA \
	uninstall-dist_mimeDATA uninstall-man uninstall-man1

.PRECIOUS: Makefile


.rc.o:
	$(WINDRES) $< -O coff -o $@

test: mrwatchmaker-dbg
	./mrwatchmaker-dbg test
.PHONY: test

valgrind: mrwatchmaker-vlg
	valgrind --leak-check=full -v --num-callers=99 --suppressions=.valgrind.supp ./$^
.PHONY: valgrind
office: all
	@rm -rf $(OFFICE_DIR) && mkdir -p $(OFFICE_DIR)
	@cp -f mrwatchmaker$(EXEEXT) $(OFFICE_DIR)/mrwatchmaker$(EXEEXT) 2>/dev/null || true
	@cp -f reference_9oclock.png $(OFFICE_DIR)/ 2>/dev/null || true
	@cp -f README.md $(OFFICE_DIR)/ 2>/dev/null || cp -f ../README.md $(OFFICE_DIR)/ 2>/dev/null || true
	@cp -f LICENSE $(OFFICE_DIR)/ 2>/dev/null || cp -f ../LICENSE $(OFFICE_DIR)/ 2>/dev/null || true
	@test -f port.conf && cp -f port.conf $(OFFICE_DIR)/ || echo "5" > $(OFFICE_DIR)/port.conf
	@echo "MrWatchmaker 회사용 폴더" > $(OFFICE_DIR)/README_회사용.txt
	@echo "1. mrwatchmaker.exe 실행" >> $(OFFICE_DIR)/README_회사용.txt
	@echo "2. port.conf 에 COM 번호만 적기 (예: 5 = COM5)" >> $(OFFICE_DIR)/README_회사용.txt
	@echo "완료: $(OFFICE_DIR)/"
.PHONY: office

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
